export type Project = {
  slug: string;
  num: string;
  title: string;
  category: string;
  year: string;
  location: string;
  services: string[];
  tags: string[];
  description: string;
  longDescription: string[];
  quote?: string;
  coverSrc: string;
  photos: {
    src: string;
    alt: string;
    aspect: "landscape" | "portrait";
  }[];
};

export const projects: Project[] = [
  {
    slug: "casa-rio-acima",
    num: "01",
    title: "Casa Rio Acima",
    category: "Projeto paisagístico em residência",
    year: "2026",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
    ],
    quote: "O rústico e o sofisticado em completa harmonia com as montanhas, respeitando a força da paisagem natural.",
    coverSrc: "/cra00.jpeg", 
    photos: [
      { src: "/cra05.jpeg", alt: "Casa Rio Acima — ", aspect: "landscape" },
      { src: "/cra02.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
      { src: "/cra07.jpeg", alt: "Casa Rio Acima — ", aspect: "landscape" },
      { src: "/cra03.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
      { src: "/cra09.jpeg", alt: "Casa Rio Acima — ", aspect: "landscape" },
      { src: "/cra01.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
      { src: "/cra06.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
      { src: "/cra08.jpeg", alt: "Casa Rio Acima — ", aspect: "landscape" },
      { src: "/cra10.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
      { src: "/cra11.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
      { src: "/cra12.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
      { src: "/cra13.jpeg", alt: "Casa Rio Acima — ", aspect: "portrait" },
    ],
  },
  {
    slug: "hospital-sao-lucas",
    num: "02",
    title: "Hospital São Lucas",
    category: "Projeto paisagístico em área comercial",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implementação", "Manutenção"],
    tags: ["Comercial", "Jardim Terapêutico", "Institucional"],
    description:
      "A cura através da natureza: jardins terapêuticos e ambientes de acolhimento para pacientes e profissionais.",
    longDescription: [
      
    ],
    quote: "A natureza possui um poder restaurador que atua silenciosamente no bem-estar de quem a observa.",
    coverSrc: "/hospital0.png",
    photos: [
      { src: "/hospital3.png", alt: "Hospital São Lucas — ", aspect: "landscape" },
      { src: "/hospital2.png", alt: "Hospital São Lucas — ", aspect: "portrait" },
      { src: "/hospital5.png", alt: "Hospital São Lucas — ", aspect: "landscape" },
      { src: "/hospital4.png", alt: "Hospital São Lucas — ", aspect: "portrait" },
      { src: "/hospital1.png", alt: "Hospital São Lucas — ", aspect: "landscape" },
    ],
  },
  {
    slug: "automovel-club",
    num: "03",
    title: "Automóvel Club",
    category: "Paisagismo corporativo",
    year: "2022",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implementação"],
    tags: ["Paisagismo corporativo", "Projeto exclusivo", "Implementação"],
    description:
      "Um projeto que une a história e sofisticação do Automóvel Club com a linguagem contemporânea do paisagismo.",
    longDescription: [
      
    ],
    quote:
      "O projeto buscou criar um diálogo entre o ambiente construído e a natureza — onde cada planta tem uma função estética e simbólica.",
    coverSrc: "/auto01.png",
    photos: [
      { src: "/auto01.png", alt: "Automóvel Club — ", aspect: "landscape" },
      { src: "/auto2.png", alt: "Automóvel Club — ", aspect: "portrait" },
      { src: "/auto3.png", alt: "Automóvel Club — ", aspect: "portrait" },
      { src: "/auto4.png", alt: "Automóvel Club — ", aspect: "portrait" },
      { src: "/auto7.png", alt: "Automóvel Club — ", aspect: "portrait" },
    ],
  },
  {
    slug: "condominio-aldeia-da-cachoeira-das-pedras",
    num: "04",
    title: "Condomínio Aldeia da Cachoeira das Pedras",
    category: "Projeto paisagístico em residência",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "A exuberância da mata nativa trazida para o convívio diário, celebrando a liberdade da vida ao ar livre.",
    coverSrc: "/cacp04.jpeg",
    photos: [
      { src: "/cacp01.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "landscape" },
      { src: "/cacp02.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "portrait" },
      { src: "/cacp03.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "landscape" },
      { src: "/cacp05.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "landscape" },
      { src: "/cacp06.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "portrait" },
      { src: "/cacp07.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "portrait" },
      { src: "/cacp08.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "portrait" },
      { src: "/cacp00.jpeg", alt: "Condomínio Aldeia da Cachoeira das Pedras — ", aspect: "landscape" },
    ],
  },
  {
    slug: "cobertura-sion2",
    num: "01",
    title: "Cobertura Sion",
    category: "Projeto paisagístico em recidência",
    year: "2026",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
    ],
    quote: "O frescor das montanhas trazido para as alturas, criando um jardim suspenso onde a linha do horizonte se torna o único limite do seu refúgio.",
    coverSrc: "/cbs00.jpeg", 
    photos: [
      { src: "/cbs01.jpeg", alt: "Cobertura Sion — l", aspect: "landscape" },
      { src: "/cbs02.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/cbs03.jpeg", alt: "Cobertura Sion — ", aspect: "landscape" },
      { src: "/cbs05.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/cbs04.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/cbs07.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/cbs06.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/cbs08.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-passargada2",
    num: "02",
    title: "Casa Passárgada",
    category: "Projeto paisagístico em residência",
    year: "2026",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Liberdade e pertencimento traduzidos em um jardim que não impõe fronteiras com a natureza local.",
    coverSrc: "/cp00.jpeg", 
    photos: [
      { src: "/cp01.jpeg", alt: "Casa Passárgada — ", aspect: "landscape" },
      { src: "/cp02.jpeg", alt: "Casa Passárgada — ", aspect: "portrait" },
      { src: "/cp03.jpeg", alt: "Casa Passárgada — ", aspect: "portrait" },
    ],
  },
  {
    slug: "condominio-belvedere",
    num: "04",
    title: "Condomínio Belvedere",
    category: "Projeto paisagístico em área comercial",
    year: "2025",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Comercial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "A primeira impressão é viva. Um paisagismo corporativo que transmite solidez, elegância e acolhimento.",
    coverSrc: "/belve03.jpeg",
    photos: [
      { src: "/belve01.jpeg", alt: "Condomínio Belvedere — ", aspect: "landscape" },
      { src: "/belve02.jpeg", alt: "Condomínio Belvedere — ", aspect: "portrait" },
      { src: "/belve00.jpeg", alt: "Condomínio Belvedere — ", aspect: "portrait" },
      { src: "/belve04.jpeg", alt: "Condomínio Belvedere — ", aspect: "portrait" },
      { src: "/belve05.jpeg", alt: "Condomínio Belvedere — ", aspect: "landscape" },
      { src: "/belve06.jpeg", alt: "Condomínio Belvedere — ", aspect: "landscape" },
      { src: "/belve07.jpeg", alt: "Condomínio Belvedere — ", aspect: "portrait" },
      { src: "/belve09.jpeg", alt: "Condomínio Belvedere — ", aspect: "portrait" },
    ],
  },  
  {
    slug: "cobertura-jardins-sao-paulo",
    num: "05",
    title: "Cobertura Jardins São Paulo",
    category: "Projeto paisagístico em residência",
    year: "2025",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Um oásis suspenso no ritmo pulsante de São Paulo, onde a natureza dita o tempo e o silêncio impera.",
    coverSrc: "/cjsp00.jpeg",
    photos: [
      { src: "/cjsp01.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "landscape" },
      { src: "/cjsp02.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp05.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp04.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp07.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp06.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp03.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp09.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp10.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp11.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
      { src: "/cjsp12.jpeg", alt: "Cobertura Jardins SÃO PAULO — ", aspect: "portrait" },
    ],
  },

  {
    slug: "casa-azeite",
    num: "06",
    title: "Casa Azeite",
    category: "Projeto paisagístico em área comercial",
    year: "2025",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Comercial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
    ],
    quote: "A estética acolhedora reinventada em verde, recebendo cada cliente com a riqueza e o calor de um ambiente vivo.",
    coverSrc: "/caz00.jpeg", 
    photos: [
      { src: "/caz01.jpeg", alt: "Casa Azeite — l", aspect: "landscape" },
      { src: "/caz02.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz03.jpeg", alt: "Casa Azeite — ", aspect: "landscape" },
      { src: "/caz05.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz04.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz07.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz06.jpeg", alt: "Casa Azeite — ", aspect: "landscape" },
      { src: "/caz08.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz09.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz10.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz11.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz13.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz12.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz13.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz14.jpeg", alt: "Casa Azeite — ", aspect: "landscape" },
      { src: "/caz15.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
      { src: "/caz16.jpeg", alt: "Casa Azeite — ", aspect: "landscape" },
      { src: "/caz17.jpeg", alt: "Casa Azeite — ", aspect: "portrait" },
    ],
  },
  
  {
    slug: "residencial-boa-vista",
    num: "07",
    title: "Residencial Boa Vista",
    category: "Projeto paisagístico em residência",
    year: "2025",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [   
    ],
    quote: "Mais do que um espaço verde, um refúgio definitivo que transforma a casa no seu lugar favorito no mundo.",
    coverSrc: "/rbv00.jpeg", 
    photos: [
      { src: "/rbv01.jpeg", alt: "Residencial Boa Vista — ", aspect: "landscape" },
      { src: "/rbv02.jpeg", alt: "Residencial Boa Vista — ", aspect: "portrait" },
      { src: "/rbv03.jpeg", alt: "Residencial Boa Vista — ", aspect: "landscape" },
      { src: "/rbv05.jpeg", alt: "Residencial Boa Vista — ", aspect: "portrait" },
      { src: "/rbv04.jpeg", alt: "Residencial Boa Vista — ", aspect: "portrait" },
      { src: "/rbv07.jpeg", alt: "Residencial Boa Vista — ", aspect: "portrait" },
      { src: "/rbv06.jpeg", alt: "Residencial Boa Vista — ", aspect: "landscape" },
      { src: "/rbv08.jpeg", alt: "Residencial Boa Vista — ", aspect: "portrait" },
      { src: "/rbv09.jpeg", alt: "Residencial Boa Vista — ", aspect: "landscape" },
    ],
  },

  {
    slug: "casa-sao-bento",
    num: "08",
    title: "Casa São Bento",
    category: "Projeto paisagístico em residência",
    year: "2025",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
    ],
    quote: "Elegância e arquitetura em perfeita sintonia, criando um santuário verde de pura sofisticação e bem-estar na cidade.",
    coverSrc: "/csb04.jpeg", 
    photos: [
      { src: "/csb01.jpeg", alt: "Casa São Bento — l", aspect: "landscape" },
      { src: "/csb02.jpeg", alt: "Casa São Bento — ", aspect: "portrait" },
      { src: "/csb03.jpeg", alt: "Casa São Bento — ", aspect: "landscape" },
      { src: "/csb05.jpeg", alt: "Casa São Bento — ", aspect: "portrait" },
      { src: "/csb00.jpeg", alt: "Casa São Bento — ", aspect: "portrait" },
      { src: "/csb07.jpeg", alt: "Casa São Bento — ", aspect: "portrait" },
      { src: "/csb08.jpeg", alt: "Casa São Bento — ", aspect: "portrait" },
      { src: "/csb09.jpeg", alt: "Casa São Bento — ", aspect: "landscape" },
    ],
  },
  {
    slug: "casa-granja-viana-sp",
    num: "09",
    title: "Casa Granja Viana - São Paulo",
    category: "Projeto paisagístico em residência",
    year: "2025",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
    ],
    quote: "Um respiro profundo onde a arquitetura se rende à floresta, transformando o morar em uma imersão diária e absoluta na natureza.",
    coverSrc: "/cgvsp00.jpeg", 
    photos: [
      { src: "/cgvsp01.jpeg", alt: "Casa Granja Viana - São Paulo — l", aspect: "landscape" },
      { src: "/cgvsp02.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp03.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "landscape" },
      { src: "/cgvsp05.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "landscape" },
      { src: "/cgvsp04.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp07.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp06.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp08.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp09.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "landscape" },
      { src: "/cgvsp10.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp11.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp12.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
      { src: "/cgvsp13.jpeg", alt: "Casa Granja Viana - São Paulo — ", aspect: "portrait" },
    ],
  },
  {
    slug: "cobertura-lourdes",
    num: "11",
    title: "Cobertura Lourdes",
    category: "Projeto paisagístico em residência",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Sofisticação natural: o verde que abraça a arquitetura e eleva a experiência de morar com exclusividade.",
    coverSrc: "/clu00.jpeg",
    photos: [
      { src: "/clu01.jpeg", alt: "Cobertura Lourdes — ", aspect: "landscape" },
      { src: "/clu02.jpeg", alt: "Cobertura Lourdes — ", aspect: "portrait" },
      { src: "/clu03.jpeg", alt: "Cobertura Lourdes — ", aspect: "portrait" },
      { src: "/clu04.jpeg", alt: "Cobertura Lourdes — ", aspect: "portrait" },
      { src: "/clu05.jpeg", alt: "Cobertura Lourdes — ", aspect: "landscape" },
      { src: "/clu06.jpeg", alt: "Cobertura Lourdes — ", aspect: "landscape" },
      { src: "/clu07.jpeg", alt: "Cobertura Lourdes — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-bandeirantes2",
    num: "12",
    title: "Casa Bandeirantes",
    category: "Projeto paisagístico em residência",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Um oásis de serenidade na Pampulha, onde as linhas orgânicas do jardim refletem a calmaria do entorno.",
    coverSrc: "/cm00.jpeg", 
    photos: [
      { src: "/cm01.jpeg", alt: "Casa Bandeirantes — ", aspect: "landscape" },
      { src: "/cm02.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm03.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm05.jpeg", alt: "Casa Bandeirantes — ", aspect: "landscape" },
      { src: "/cm04.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm07.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm06.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm08.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm09.jpeg", alt: "Casa Bandeirantes — ", aspect: "landscape" },
      { src: "/cm10.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm011.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/cm12.jpeg", alt: "Casa Bandeirantes — ", aspect: "landscape" },
      { src: "/cm13.jpeg", alt: "Casa Bandeirantes — ", aspect: "portrait" },
    ],
  },

  {
    slug: "condominio-victoria-golf-lagoa-santa",
    num: "14",
    title: "Condomínio Victoria Golf - Lagoa Santa",
    category: "Projeto paisagístico em residência",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "A amplitude do horizonte encontra o rigor estético, resultando em um paisagismo que convida à contemplação.",
    coverSrc: "/cvgls00.jpeg", 
    photos: [
      { src: "/cvgls01.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "landscape" },
      { src: "/cvgls02.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "portrait" },
      { src: "/cvgls03.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "landscape" },
      { src: "/cvgls05.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "landscape" },
      { src: "/cvgls04.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "portrait" },
      { src: "/cvgls07.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "portrait" },
      { src: "/cvgls06.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "landscape" },
      { src: "/cvgls08.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "portrait" },
      { src: "/cvgls09.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "landscape" },
      { src: "/cvgls10.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "portrait" },
      { src: "/cvgls11.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "portrait" },
      { src: "/cvgls12.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "landscape" },
      { src: "/cvgls13.jpeg", alt: "Condomínio Victoria Golf - LAGOA SANTA — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-xangrila",
    num: "15",
    title: "Casa Xangrilá",
    category: "Projeto paisagístico em residência",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Um santuário particular. O paisagismo que funciona como um convite diário para a pausa e a reconexão.",
    coverSrc: "/cx00.jpeg", 
    photos: [
      { src: "/cx03.jpeg", alt: "Casa Xangrilá — ", aspect: "landscape" },
      { src: "/cx02.jpeg", alt: "Casa Xangrilá — ", aspect: "portrait" },
      { src: "/cx01.jpeg", alt: "Casa Xangrilá — ", aspect: "portrait" },
      { src: "/cx05.jpeg", alt: "Casa Xangrilá — ", aspect: "landscape" },
      { src: "/cx04.jpeg", alt: "Casa Xangrilá — ", aspect: "portrait" },
      { src: "/cx07.jpeg", alt: "Casa Xangrilá — ", aspect: "portrait" },
      { src: "/cx06.jpeg", alt: "Casa Xangrilá — ", aspect: "landscape" },
      { src: "/cx08.jpeg", alt: "Casa Xangrilá — ", aspect: "portrait" },
      { src: "/cx12.jpeg", alt: "Casa Xangrilá — ", aspect: "landscape" },
      { src: "/cx10.jpeg", alt: "Casa Xangrilá — ", aspect: "portrait" },
      { src: "/cx11.jpeg", alt: "Casa Xangrilá — ", aspect: "portrait" },
      { src: "/cx09.jpeg", alt: "Casa Xangrilá — ", aspect: "landscape" },
    ],
  },
  {
    slug: "casa-jaboticatubas",
    num: "16",
    title: "Casa Jaboticatubas",
    category: "Projeto paisagístico em residência",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
    ],
    quote: "A imensidão e a força da natureza local traduzidas em um paisagismo que faz do horizonte a extensão do próprio lar.",
    coverSrc: "/cj00.jpeg", 
    photos: [
      { src: "/cj01.jpeg", alt: "Casa Jaboticatubas — l", aspect: "landscape" },
      { src: "/cj02.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj03.jpeg", alt: "Casa Jaboticatubas — ", aspect: "landscape" },
      { src: "/cj05.jpeg", alt: "Casa Jaboticatubas — ", aspect: "landscape" },
      { src: "/cj04.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj07.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj06.jpeg", alt: "Casa Jaboticatubas — ", aspect: "landscape" },
      { src: "/cj08.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj09.jpeg", alt: "Casa Jaboticatubas — ", aspect: "landscape" },
      { src: "/cj10.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj11.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj12.jpeg", alt: "Casa Jaboticatubas — ", aspect: "landscape" },
      { src: "/cj13.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj13.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj14.jpeg", alt: "Casa Jaboticatubas — ", aspect: "landscape" },
      { src: "/cj15.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
      { src: "/cj17.jpeg", alt: "Casa Jaboticatubas — ", aspect: "portrait" },
    ],
  },
  {
    slug: "solar-da-pianista-ouro-preto",
    num: "17",
    title: "Solar da Pianista - Ouro Preto",
    category: "Projeto paisagístico área comercial",
    year: "2024",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Comercial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
    ],
    quote: "Notas de verde que dialogam com a história. Um paisagismo sensível que honra a alma colonial e compõe a atmosfera perfeita para o encontro e a arte.",
    coverSrc: "/spop00.jpeg", 
    photos: [
      { src: "/spop01.jpeg", alt: "Solar da Pianista - Ouro Preto — l", aspect: "landscape" },
      { src: "/spop02.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop03.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop05.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop04.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop07.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop06.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop08.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop09.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "landscape" },
      { src: "/spop10.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop12.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
      { src: "/spop13.jpeg", alt: "Solar da Pianista - Ouro Preto — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-mangabeiras",
    num: "18",
    title: "Casa Mangabeiras",
    category: "Projeto paisagístico em residência",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implementação", "Manutenção"],
    tags: ["Residencial", "Área Externa", "Jardim Tropical"],
    description:
      "Um oásis particular no bairro Mangabeiras, integrando a arquitetura da casa com a exuberância da flora local.",
    longDescription: [
      
    ],
    quote: "A natureza não apenas contorna a casa, ela a abraça e redefine a forma de viver o espaço exterior.",
    coverSrc: "/mangabeiras0.png",
    photos: [
      { src: "/mangabeiras2.png", alt: "Casa Mangabeiras — ", aspect: "landscape" },
      { src: "/mangabeiras1.png", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mangabeiras5.png", alt: "Casa Mangabeiras — ", aspect: "landscape" },
      { src: "/mangabeiras3.png", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mangabeiras6.png", alt: "Casa Mangabeiras — ", aspect: "landscape" },
    ],
  },
  {
    slug: "orby-academy",
    num: "19",
    title: "Órby Academy",
    category: "Projeto paisagístico em área comercial",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Comercial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Inovação e natureza lado a lado: um ecossistema projetado para inspirar mentes criativas e oxigenar ideias.",
    coverSrc: "/oa00.jpeg",
    photos: [
      { src: "/oa01.jpeg", alt: "Órby Academy — ", aspect: "landscape" },
      { src: "/oa02.jpeg", alt: "Órby Academy — ", aspect: "portrait" },
      { src: "/oa03.jpeg", alt: "Órby Academy — ", aspect: "landscape" },
      { src: "/oa05.jpeg", alt: "Órby Academy — ", aspect: "landscape" },
      { src: "/oa04.jpeg", alt: "Órby Academy — ", aspect: "portrait" },
      { src: "/oa07.jpeg", alt: "Órby Academy — ", aspect: "portrait" },
      { src: "/oa06.jpeg", alt: "Órby Academy — ", aspect: "landscape" },
      { src: "/oa08.jpeg", alt: "Órby Academy — ", aspect: "portrait" },
    ],
  },
  {
    slug: "restaurante-kanpai-lourdes",
    num: "20",
    title: "Restaurante Kanpai Lourdes",
    category: "Projeto paisagístico em área comercial",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Comercial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Uma experiência sensorial completa, onde a alta gastronomia oriental e a harmonia botânica se tornam uma coisa só.",
    coverSrc: "/rkl00.jpeg",
    photos: [
      { src: "/rkl01.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl02.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl03.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl04.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl05.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl06.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl07.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl08.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl09.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl10.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl11.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl12.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl13.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
      { src: "/rkl14.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl15.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl17.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "portrait" },
      { src: "/rkl16.jpeg", alt: "Restaurante KANPAI Lourdes — ", aspect: "landscape" },
    ],
  },
  {
    slug: "casa-santo-antonio",
    num: "21",
    title: "Casa Santo Antônio",
    category: "Projeto paisagístico em residência",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "A tradição e o frescor contemporâneo se encontram em um jardim feito para colecionar memórias em família.",
    coverSrc: "/sant00.jpeg",
    photos: [
      { src: "/sant01.jpeg", alt: "Casa Santo Antônio — ", aspect: "landscape" },
      { src: "/sant02.jpeg", alt: "Casa Santo Antônio — ", aspect: "portrait" },
      { src: "/sant03.jpeg", alt: "Casa Santo Antônio — ", aspect: "landscape" },
      { src: "/sant04.jpeg", alt: "Casa Santo Antônio — ", aspect: "portrait" },
      { src: "/sant05.jpeg", alt: "Casa Santo Antônio — ", aspect: "landscape" },
      { src: "/sant06.jpeg", alt: "Casa Santo Antônio — ", aspect: "landscape" },
    ],
  },

  {
    slug: "condominio-canto-das-agua",
    num: "22",
    title: "Condomínio Canto das Água",
    category: "Projeto paisagístico em residência",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "A arquitetura se curva à grandiosidade da natureza, criando um diálogo ininterrupto com a paisagem ao redor.",
    coverSrc: "/cca00.jpeg",
    photos: [
      { src: "/cca01.jpeg", alt: "Condomínio Canto das Água — ", aspect: "landscape" },
      { src: "/cca02.jpeg", alt: "Condomínio Canto das Água — ", aspect: "portrait" },
      { src: "/cca03.jpeg", alt: "Condomínio Canto das Água — ", aspect: "landscape" },
      { src: "/cca05.jpeg", alt: "Condomínio Canto das Água — ", aspect: "landscape" },
      { src: "/cca04.jpeg", alt: "Condomínio Canto das Água — ", aspect: "portrait" },
      { src: "/cca07.jpeg", alt: "Condomínio Canto das Água — ", aspect: "portrait" },
      { src: "/cca06.jpeg", alt: "Condomínio Canto das Água — ", aspect: "landscape" },
      { src: "/cca09.jpeg", alt: "Condomínio Canto das Água — ", aspect: "landscape" },
      { src: "/cca08.jpeg", alt: "Condomínio Canto das Água — ", aspect: "portrait" },
    ],
  },
  {
    slug: "cobertura-anchieta",
    num: "23",
    title: "Cobertura Anchieta",
    category: "Projeto paisagístico em residência",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Privacidade esculpida em folhas e texturas, transformando a vista panorâmica em um quadro vivo.",
    coverSrc: "/ca00.jpeg",
    photos: [
      { src: "/ca01.jpeg", alt: "Cobertura Anchieta — ", aspect: "landscape" },
      { src: "/ca02.jpeg", alt: "Cobertura Anchieta — ", aspect: "portrait" },
      { src: "/ca03.jpeg", alt: "Cobertura Anchieta — ", aspect: "portrait" },
      { src: "/ca05.jpeg", alt: "Cobertura Anchieta — ", aspect: "landscape" },
      { src: "/ca04.jpeg", alt: "Cobertura Anchieta — ", aspect: "portrait" },
      { src: "/ca07.jpeg", alt: "Cobertura Anchieta — ", aspect: "portrait" },
      { src: "/ca06.jpeg", alt: "Cobertura Anchieta — ", aspect: "landscape" },
      { src: "/ca09.jpeg", alt: "Cobertura Anchieta — ", aspect: "landscape" },
      { src: "/ca08.jpeg", alt: "Cobertura Anchieta — ", aspect: "portrait" },
      { src: "/ca10.jpeg", alt: "Cobertura Anchieta — ", aspect: "portrait" },
    ],
  },
  
  {
    slug: "apartamento-lourdes",
    num: "24",
    title: "Apartamento Lourdes",
    category: "Projeto paisagístico em residência",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "O design biofílico levado à sua máxima elegância, provando que a natureza é a alma dos interiores.",
    coverSrc: "/apl00.jpeg",
    photos: [
      { src: "/apl01.jpeg", alt: "Apartamento Lourdes — ", aspect: "landscape" },
      { src: "/apl02.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/apl03.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/apl05.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/apl04.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/apl07.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/apl06.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/apl08.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-santa-tereza",
    num: "25",
    title: "Casa Santa Tereza",
    category: "Projeto paisagístico em residência",
    year: "2023",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "O design biofílico levado à sua máxima elegância, provando que a natureza é a alma dos interiores.",
    coverSrc: "/cst00.jpeg",
    photos: [
      { src: "/cst01.jpeg", alt: "Apartamento Lourdes — ", aspect: "landscape" },
      { src: "/cst02.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/cst03.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/cst05.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/cst04.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/cst07.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/cst06.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
      { src: "/cst08.jpeg", alt: "Apartamento Lourdes — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-retiro-do-chale",
    num: "26",
    title: "Casa Retiro do Chalé",
    category: "Projeto paisagístico em residência",
    year: "2022",
    location: "Brumadinho, MG",
    services: ["Criação", "Implementação"],
    tags: ["Residencial", "Serra", "Integração Natural"],
    description:
      "Intervenção sutil que respeita e valoriza a paisagem exuberante e nativa do Retiro do Chalé.",
    longDescription: [
      
    ],
    quote: "O melhor paisagismo em áreas de serra é aquele que parece sempre ter estado ali.",
    coverSrc: "/chale4.png",
    photos: [
      { src: "/chale3.png", alt: "Casa Retiro do Chalé — ", aspect: "landscape" },
      { src: "/chale1.png", alt: "Casa Retiro do Chalé — ", aspect: "portrait" },
      { src: "/chale0.png", alt: "Casa Retiro do Chalé — ", aspect: "landscape" },
      { src: "/chale5.png", alt: "Casa Retiro do Chalé — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-bandeirantes",
    num: "27",
    title: "Casa Bandeirantes",
    category: "Projeto paisagístico em residência",
    year: "2022",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implementação", "Manutenção"],
    tags: ["Residencial", "Pampulha", "Clássico Contemporâneo"],
    description:
      "A fluidez das formas em um paisagismo pensado para a tradicional região da Pampulha.",
    longDescription: [
      
    ],
    quote: "A fluidez do jardim acompanha o ritmo tranquilo da arquitetura que o rodeia.",
    coverSrc: "/bandeirantes1.png",
    photos: [
      { src: "/bandeirantes0.png", alt: "Casa Bandeirantes — ", aspect: "landscape" },
      { src: "/bandeirantes2.png", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/bandeirantes5.png", alt: "Casa Bandeirantes — ", aspect: "landscape" },
      { src: "/bandeirantes4.png", alt: "Casa Bandeirantes — ", aspect: "portrait" },
      { src: "/bandeirantes3.png", alt: "Casa Bandeirantes — ", aspect: "landscape" },
    ],
  },
  {
    slug: "apartamento-serra",
    num: "28",
    title: "Apartamento Serra",
    category: "Projeto paisagístico em residência",
    year: "2022",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Curadoria botânica"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "O verde indoor transforma a casa em um lar, trazendo vitalidade para o dia a dia.",
    coverSrc: "/serra0.png",
    photos: [
      { src: "/serra1.png", alt: "Apartamento Serra — ", aspect: "landscape" },
      { src: "/serra5.png", alt: "Apartamento Serra — ", aspect: "portrait" },
      { src: "/serra7.png", alt: "Apartamento Serra — ", aspect: "landscape" },
      { src: "/serra2.png", alt: "Apartamento Serra — ", aspect: "portrait" },
      { src: "/serra3.png", alt: "Apartamento Serra — ", aspect: "landscape" },
    ],
  },
  {
    slug: "apartamento-santo-antonio",
    num: "29",
    title: "Apartamento Santo Antônio",
    category: "Projeto paisagístico em residência",
    year: "2022",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Trazer o verde para as alturas é criar um refúgio particular de silêncio e vida no coração do bairro.",
    coverSrc: "/st00.jpeg",
    photos: [
      { src: "/st01.jpeg", alt: "Apartamento Santo Antônio — ", aspect: "landscape" },
      { src: "/st02.jpeg", alt: "Apartamento Santo Antônio — ", aspect: "portrait" },
      { src: "/st05.jpeg", alt: "Apartamento Santo Antônio — ", aspect: "landscape" },
      { src: "/st04.jpeg", alt: "Apartamento Santo Antônio — ", aspect: "portrait" },
      { src: "/st03.jpeg", alt: "Apartamento Santo Antônio — ", aspect: "portrait" },
    ],
  },
  {
    slug: "apartamento-savassi",
    num: "30",
    title: "Apartamento Savassi",
    category: "Projeto paisagístico em residência",
    year: "2022",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "O contraponto perfeito à vida urbana: um respiro verde dentro da efervescência da cidade.",
    coverSrc: "/aps00.jpeg",
    photos: [
      { src: "/aps01.jpeg", alt: "Apartamento Savassi — ", aspect: "landscape" },
      { src: "/aps02.jpeg", alt: "Apartamento Savassi — ", aspect: "portrait" },
      { src: "/aps03.jpeg", alt: "Apartamento Savassi — ", aspect: "landscape" },
      { src: "/aps05.jpeg", alt: "Apartamento Savassi — ", aspect: "portrait" },
      { src: "/aps04.jpeg", alt: "Apartamento Savassi — ", aspect: "portrait" },
      { src: "/aps07.jpeg", alt: "Apartamento Savassi — ", aspect: "portrait" },
      { src: "/aps06.jpeg", alt: "Apartamento Savassi — ", aspect: "landscape" },
      { src: "/aps09.jpeg", alt: "Apartamento Savassi — ", aspect: "landscape" },
      { src: "/aps08.jpeg", alt: "Apartamento Savassi — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casa-passargada",
    num: "32",
    title: "Casa Passargada",
    category: "Projeto paisagístico em residência",
    year: "2021",
    location: "Nova Lima, MG",
    services: ["Criação", "Implementação", "Manutenção"],
    tags: ["Residencial", "Contemporâneo", "Minimalista"],
    description:
      "Linhas limpas e escolha botânica precisa marcam este projeto de paisagismo contemporâneo.",
    longDescription: [
      
    ],
    quote: "A simplicidade é o mais alto grau de sofisticação, e isso se reflete na escolha de cada espécie deste jardim.",
    coverSrc: "/passargada0.png",
    photos: [
      { src: "/passargada1.png", alt: "Casa Passargada — ", aspect: "landscape" },
      { src: "/passargada4.png", alt: "Casa Passargada — ", aspect: "portrait" },
      { src: "/passargada3.png", alt: "Casa Passargada — ", aspect: "landscape" },
      { src: "/passargada2.png", alt: "Casa Passargada — ", aspect: "portrait" },
      { src: "/passargada5.png", alt: "Casa Passargada — ", aspect: "landscape" },
    ],
  },

  {
    slug: "casa-glaura",
    num: "33",
    title: "Casa Glaura",
    category: "Projeto paisagístico em residência",
    year: "2021",
    location: "Ouro Preto, MG",
    services: ["Criação", "Implementação"],
    tags: ["Residencial", "Histórico", "Jardim de Inverno"],
    description:
      "Um diálogo entre a arquitetura de traços históricos e o frescor de um paisagismo afetivo e acolhedor.",
    longDescription: [
      
    ],
    quote: "Um jardim que respeita a memória do lugar constrói raízes ainda mais profundas.",
    coverSrc: "/glaura4.png",
    photos: [
      { src: "/glaura3.png", alt: "Casa Glaura — ", aspect: "landscape" },
      { src: "/glaura2.png", alt: "Casa Glaura — ", aspect: "portrait" },
      { src: "/glaura1.png", alt: "Casa Glaura — ", aspect: "landscape" },
      { src: "/glaura0.png", alt: "Casa Glaura — ", aspect: "portrait" },
      { src: "/glaura5.png", alt: "Casa Glaura — ", aspect: "landscape" },
    ],
  },

  {
    slug: "casa-retiro-das-pedras",
    num: "34",
    title: "Casa Retiro das Pedras",
    category: "Projeto paisagístico em residência",
    year: "2021",
    location: "Brumadinho, MG",
    services: ["Criação", "Implementação"],
    tags: ["Residencial", "Integração Natural", "Espécies Nativas"],
    description:
      "Paisagismo de impacto que dialoga com a imponência do condomínio Retiro das Pedras.",
    longDescription: [
      
    ],
    quote: "A moldura perfeita para uma vista definitiva é aquela desenhada com vida e texturas naturais.",
    coverSrc: "/pedras0.png",
    photos: [
      { src: "/pedras1.png", alt: "Casa Retiro das Pedras — ", aspect: "landscape" },
      { src: "/pedras2.png", alt: "Casa Retiro das Pedras — ", aspect: "portrait" },
      { src: "/pedras4.png", alt: "Casa Retiro das Pedras — ", aspect: "landscape" },
      { src: "/pedras5.png", alt: "Casa Retiro das Pedras — ", aspect: "portrait" },
      { src: "/pedras7.png", alt: "Casa Retiro das Pedras — ", aspect: "landscape" },
    ],
  },
  {
    slug: "casa-mangabeiras2",
    num: "35",
    title: "Casa Mangabeiras",
    category: "Projeto paisagístico em área comercial",
    year: "2021",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Comercial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "Um ambiente de negócios que respira. A natureza atuando como aliada da criatividade e do bem-estar.",
    coverSrc: "/mang00.jpeg",
    photos: [
      { src: "/mang01.jpeg", alt: "Casa Mangabeiras — ", aspect: "landscape" },
      { src: "/mang02.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang03.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang04.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang05.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang06.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang07.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang08.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang09.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang11.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
      { src: "/mang10.jpeg", alt: "Casa Mangabeiras — ", aspect: "portrait" },
    ],
  },
  {
    slug: "area-privativa-savassi",
    num: "36",
    title: "Área Privativa Savassi",
    category: "Projeto paisagístico em residência",
    year: "2020",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implementação", "Manutenção"],
    tags: ["Residencial", "Apartamento", "Urban Jungle"],
    description:
      "Otimização de espaço e criação de um oásis urbano no coração da Savassi.",
    longDescription: [
      
    ],
    quote: "No centro da cidade, o verdadeiro luxo é abrir a porta e encontrar o próprio jardim.",
    coverSrc: "/savassi0.png",
    photos: [
      { src: "/savassi0.png", alt: "Área Privativa Savassi — ", aspect: "landscape" },
      { src: "/savassi1.png", alt: "Área Privativa Savassi — ", aspect: "portrait" },
      { src: "/savassi2.png", alt: "Área Privativa Savassi — ", aspect: "landscape" },
      { src: "/savassi3.png", alt: "Área Privativa Savassi — ", aspect: "portrait" },
      { src: "/savassi4.png", alt: "Área Privativa Savassi — ", aspect: "landscape" },
    ],
  },

  {
    slug: "cobertura-sion",
    num: "37",
    title: "Cobertura Sion",
    category: "Projeto paisagístico em residência",
    year: "2020",
    location: "Belo Horizonte, MG",
    services: ["Criação", "Implantação", "Manutenção"],
    tags: ["Residencial", "Indoor", "Curadoria"],
    description:
      "Elegância botânica indoor: plantas selecionadas para complementar o design de interiores.",
    longDescription: [
          ],
    quote: "O horizonte da cidade ganha uma nova moldura quando o paisagismo se funde perfeitamente com o céu.",
    coverSrc: "/sion00.jpeg",
    photos: [
      { src: "/sion01.jpeg", alt: "Cobertura Sion — ", aspect: "landscape" },
      { src: "/sion02.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/sion03.jpeg", alt: "Cobertura Sion — ", aspect: "landscape" },
      { src: "/sion04.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/sion05.jpeg", alt: "Cobertura Sion — ", aspect: "landscape" },
      { src: "/sion06.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/sion07.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
      { src: "/sion08.jpeg", alt: "Cobertura Sion — ", aspect: "landscape" },
      { src: "/sion09.jpeg", alt: "Cobertura Sion — ", aspect: "portrait" },
    ],
  },
  {
    slug: "casacor-2019",
    num: "38",
    title: "Casacor 2019",
    category: "Evento & Design de Interiores Verdes",
    year: "2019",
    location: "Belo Horizonte, MG",
    services: ["Consultoria", "Criação", "Curadoria botânica"],
    tags: ["Jardim interno", "Consultoria", "Curadoria botânica"],
    description:
      "Participação no maior evento de arquitetura e design da América Latina, com um ambiente que traduziu em plantas e formas a essência da Plante Comigo.",
    longDescription: [
     
    ],
    quote:
      "A Casacor foi uma oportunidade de mostrar que o paisagismo é também linguagem — uma forma de comunicar valores e criar experiências memoráveis.",
    coverSrc: "/casacor0.png",
    photos: [
      { src: "/casacor1.png", alt: "Casacor 2019 — ", aspect: "landscape" },
      { src: "/casacor5.png", alt: "Casacor 2019 — ", aspect: "portrait" },
      { src: "/casacor4.png", alt: "Casacor 2019 — ", aspect: "portrait" },
      { src: "/casacor3.png", alt: "Casacor 2019 — ", aspect: "portrait" },
      { src: "/casacor2.png", alt: "Casacor 2019 — ", aspect: "portrait" },
    ],
  },
  {
    slug: "guaja-casa",
    num: "39",
    title: "GUAJA Casa",
    category: "Projeto paisagístico em área comercial",
    year: "2019",
    location: "Belo Horizonte, MG",
    services: ["Consultoria", "Criação", "Implementação"],
    tags: ["Comercial", "Biofilia", "Ambiente Criativo"],
    description:
      "Transformando um hub de inovação e criatividade através do design biofílico e da conexão com o verde.",
    longDescription: [
      
    ],
    quote: "A introdução da natureza em ambientes de trabalho não é luxo, é uma ferramenta essencial para a inovação.",
    coverSrc: "/guaja0.png",
    photos: [
      { src: "/guaja1.png", alt: "GUAJA Casa — ", aspect: "landscape" },
      { src: "/guaja2.png", alt: "GUAJA Casa — ", aspect: "portrait" },
      { src: "/guaja3.png", alt: "GUAJA Casa — ", aspect: "landscape" },
      { src: "/guaja4.png", alt: "GUAJA Casa — ", aspect: "portrait" },
      { src: "/guaja6.png", alt: "GUAJA Casa — ", aspect: "landscape" },
    ],
  },    
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getAdjacentProjects(slug: string): {
  prev: Project | null;
  next: Project | null;
} {
  const index = projects.findIndex((p) => p.slug === slug);
  return {
    prev: index > 0 ? projects[index - 1] : null,
    next: index < projects.length - 1 ? projects[index + 1] : null,
  };
}
